# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/conda/bin/cmake

# The command to remove a file.
RM = /opt/conda/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lvtingxun/Project/tools/faiss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lvtingxun/Project/tools/faiss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/conda/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/conda/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/conda/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/conda/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/conda/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/conda/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lvtingxun/Project/tools/faiss/CMakeFiles /home/lvtingxun/Project/tools/faiss//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lvtingxun/Project/tools/faiss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named faiss

# Build rule for target.
faiss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss
.PHONY : faiss

# fast build rule for target.
faiss/fast:
	$(MAKE) $(MAKESILENT) -f faiss/CMakeFiles/faiss.dir/build.make faiss/CMakeFiles/faiss.dir/build
.PHONY : faiss/fast

#=============================================================================
# Target rules for targets named swigfaiss_swig_compilation

# Build rule for target.
swigfaiss_swig_compilation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swigfaiss_swig_compilation
.PHONY : swigfaiss_swig_compilation

# fast build rule for target.
swigfaiss_swig_compilation/fast:
	$(MAKE) $(MAKESILENT) -f faiss/python/CMakeFiles/swigfaiss_swig_compilation.dir/build.make faiss/python/CMakeFiles/swigfaiss_swig_compilation.dir/build
.PHONY : swigfaiss_swig_compilation/fast

#=============================================================================
# Target rules for targets named faiss_python_callbacks

# Build rule for target.
faiss_python_callbacks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss_python_callbacks
.PHONY : faiss_python_callbacks

# fast build rule for target.
faiss_python_callbacks/fast:
	$(MAKE) $(MAKESILENT) -f faiss/python/CMakeFiles/faiss_python_callbacks.dir/build.make faiss/python/CMakeFiles/faiss_python_callbacks.dir/build
.PHONY : faiss_python_callbacks/fast

#=============================================================================
# Target rules for targets named swigfaiss

# Build rule for target.
swigfaiss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swigfaiss
.PHONY : swigfaiss

# fast build rule for target.
swigfaiss/fast:
	$(MAKE) $(MAKESILENT) -f faiss/python/CMakeFiles/swigfaiss.dir/build.make faiss/python/CMakeFiles/swigfaiss.dir/build
.PHONY : swigfaiss/fast

#=============================================================================
# Target rules for targets named demo_sift1M

# Build rule for target.
demo_sift1M: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_sift1M
.PHONY : demo_sift1M

# fast build rule for target.
demo_sift1M/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/demo_sift1M.dir/build.make demos/CMakeFiles/demo_sift1M.dir/build
.PHONY : demo_sift1M/fast

#=============================================================================
# Target rules for targets named demo_weighted_kmeans

# Build rule for target.
demo_weighted_kmeans: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_weighted_kmeans
.PHONY : demo_weighted_kmeans

# fast build rule for target.
demo_weighted_kmeans/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/demo_weighted_kmeans.dir/build.make demos/CMakeFiles/demo_weighted_kmeans.dir/build
.PHONY : demo_weighted_kmeans/fast

#=============================================================================
# Target rules for targets named demo_imi_flat

# Build rule for target.
demo_imi_flat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_imi_flat
.PHONY : demo_imi_flat

# fast build rule for target.
demo_imi_flat/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/demo_imi_flat.dir/build.make demos/CMakeFiles/demo_imi_flat.dir/build
.PHONY : demo_imi_flat/fast

#=============================================================================
# Target rules for targets named demo_ivfpq_indexing

# Build rule for target.
demo_ivfpq_indexing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_ivfpq_indexing
.PHONY : demo_ivfpq_indexing

# fast build rule for target.
demo_ivfpq_indexing/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/demo_ivfpq_indexing.dir/build.make demos/CMakeFiles/demo_ivfpq_indexing.dir/build
.PHONY : demo_ivfpq_indexing/fast

#=============================================================================
# Target rules for targets named demo_imi_pq

# Build rule for target.
demo_imi_pq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_imi_pq
.PHONY : demo_imi_pq

# fast build rule for target.
demo_imi_pq/fast:
	$(MAKE) $(MAKESILENT) -f demos/CMakeFiles/demo_imi_pq.dir/build.make demos/CMakeFiles/demo_imi_pq.dir/build
.PHONY : demo_imi_pq/fast

#=============================================================================
# Target rules for targets named 5-Multiple-GPUs

# Build rule for target.
5-Multiple-GPUs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 5-Multiple-GPUs
.PHONY : 5-Multiple-GPUs

# fast build rule for target.
5-Multiple-GPUs/fast:
	$(MAKE) $(MAKESILENT) -f tutorial/cpp/CMakeFiles/5-Multiple-GPUs.dir/build.make tutorial/cpp/CMakeFiles/5-Multiple-GPUs.dir/build
.PHONY : 5-Multiple-GPUs/fast

#=============================================================================
# Target rules for targets named 4-GPU

# Build rule for target.
4-GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 4-GPU
.PHONY : 4-GPU

# fast build rule for target.
4-GPU/fast:
	$(MAKE) $(MAKESILENT) -f tutorial/cpp/CMakeFiles/4-GPU.dir/build.make tutorial/cpp/CMakeFiles/4-GPU.dir/build
.PHONY : 4-GPU/fast

#=============================================================================
# Target rules for targets named 2-IVFFlat

# Build rule for target.
2-IVFFlat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 2-IVFFlat
.PHONY : 2-IVFFlat

# fast build rule for target.
2-IVFFlat/fast:
	$(MAKE) $(MAKESILENT) -f tutorial/cpp/CMakeFiles/2-IVFFlat.dir/build.make tutorial/cpp/CMakeFiles/2-IVFFlat.dir/build
.PHONY : 2-IVFFlat/fast

#=============================================================================
# Target rules for targets named 3-IVFPQ

# Build rule for target.
3-IVFPQ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3-IVFPQ
.PHONY : 3-IVFPQ

# fast build rule for target.
3-IVFPQ/fast:
	$(MAKE) $(MAKESILENT) -f tutorial/cpp/CMakeFiles/3-IVFPQ.dir/build.make tutorial/cpp/CMakeFiles/3-IVFPQ.dir/build
.PHONY : 3-IVFPQ/fast

#=============================================================================
# Target rules for targets named 1-Flat

# Build rule for target.
1-Flat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1-Flat
.PHONY : 1-Flat

# fast build rule for target.
1-Flat/fast:
	$(MAKE) $(MAKESILENT) -f tutorial/cpp/CMakeFiles/1-Flat.dir/build.make tutorial/cpp/CMakeFiles/1-Flat.dir/build
.PHONY : 1-Flat/fast

#=============================================================================
# Target rules for targets named faiss_test

# Build rule for target.
faiss_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss_test
.PHONY : faiss_test

# fast build rule for target.
faiss_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/faiss_test.dir/build.make tests/CMakeFiles/faiss_test.dir/build
.PHONY : faiss_test/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named TestGpuMemoryException

# Build rule for target.
TestGpuMemoryException: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuMemoryException
.PHONY : TestGpuMemoryException

# fast build rule for target.
TestGpuMemoryException/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuMemoryException.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuMemoryException.dir/build
.PHONY : TestGpuMemoryException/fast

#=============================================================================
# Target rules for targets named TestGpuDistance

# Build rule for target.
TestGpuDistance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuDistance
.PHONY : TestGpuDistance

# fast build rule for target.
TestGpuDistance/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuDistance.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuDistance.dir/build
.PHONY : TestGpuDistance/fast

#=============================================================================
# Target rules for targets named TestGpuIndexBinaryFlat

# Build rule for target.
TestGpuIndexBinaryFlat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuIndexBinaryFlat
.PHONY : TestGpuIndexBinaryFlat

# fast build rule for target.
TestGpuIndexBinaryFlat/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuIndexBinaryFlat.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuIndexBinaryFlat.dir/build
.PHONY : TestGpuIndexBinaryFlat/fast

#=============================================================================
# Target rules for targets named TestGpuIndexIVFFlat

# Build rule for target.
TestGpuIndexIVFFlat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuIndexIVFFlat
.PHONY : TestGpuIndexIVFFlat

# fast build rule for target.
TestGpuIndexIVFFlat/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuIndexIVFFlat.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuIndexIVFFlat.dir/build
.PHONY : TestGpuIndexIVFFlat/fast

#=============================================================================
# Target rules for targets named faiss_gpu_test_helper

# Build rule for target.
faiss_gpu_test_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faiss_gpu_test_helper
.PHONY : faiss_gpu_test_helper

# fast build rule for target.
faiss_gpu_test_helper/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/faiss_gpu_test_helper.dir/build.make faiss/gpu/test/CMakeFiles/faiss_gpu_test_helper.dir/build
.PHONY : faiss_gpu_test_helper/fast

#=============================================================================
# Target rules for targets named TestGpuIndexFlat

# Build rule for target.
TestGpuIndexFlat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuIndexFlat
.PHONY : TestGpuIndexFlat

# fast build rule for target.
TestGpuIndexFlat/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuIndexFlat.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuIndexFlat.dir/build
.PHONY : TestGpuIndexFlat/fast

#=============================================================================
# Target rules for targets named TestGpuIndexIVFPQ

# Build rule for target.
TestGpuIndexIVFPQ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuIndexIVFPQ
.PHONY : TestGpuIndexIVFPQ

# fast build rule for target.
TestGpuIndexIVFPQ/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuIndexIVFPQ.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuIndexIVFPQ.dir/build
.PHONY : TestGpuIndexIVFPQ/fast

#=============================================================================
# Target rules for targets named TestGpuIndexIVFScalarQuantizer

# Build rule for target.
TestGpuIndexIVFScalarQuantizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuIndexIVFScalarQuantizer
.PHONY : TestGpuIndexIVFScalarQuantizer

# fast build rule for target.
TestGpuIndexIVFScalarQuantizer/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuIndexIVFScalarQuantizer.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuIndexIVFScalarQuantizer.dir/build
.PHONY : TestGpuIndexIVFScalarQuantizer/fast

#=============================================================================
# Target rules for targets named TestGpuSelect

# Build rule for target.
TestGpuSelect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGpuSelect
.PHONY : TestGpuSelect

# fast build rule for target.
TestGpuSelect/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/TestGpuSelect.dir/build.make faiss/gpu/test/CMakeFiles/TestGpuSelect.dir/build
.PHONY : TestGpuSelect/fast

#=============================================================================
# Target rules for targets named demo_ivfpq_indexing_gpu

# Build rule for target.
demo_ivfpq_indexing_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demo_ivfpq_indexing_gpu
.PHONY : demo_ivfpq_indexing_gpu

# fast build rule for target.
demo_ivfpq_indexing_gpu/fast:
	$(MAKE) $(MAKESILENT) -f faiss/gpu/test/CMakeFiles/demo_ivfpq_indexing_gpu.dir/build.make faiss/gpu/test/CMakeFiles/demo_ivfpq_indexing_gpu.dir/build
.PHONY : demo_ivfpq_indexing_gpu/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... swigfaiss_swig_compilation"
	@echo "... 1-Flat"
	@echo "... 2-IVFFlat"
	@echo "... 3-IVFPQ"
	@echo "... 4-GPU"
	@echo "... 5-Multiple-GPUs"
	@echo "... TestGpuDistance"
	@echo "... TestGpuIndexBinaryFlat"
	@echo "... TestGpuIndexFlat"
	@echo "... TestGpuIndexIVFFlat"
	@echo "... TestGpuIndexIVFPQ"
	@echo "... TestGpuIndexIVFScalarQuantizer"
	@echo "... TestGpuMemoryException"
	@echo "... TestGpuSelect"
	@echo "... demo_imi_flat"
	@echo "... demo_imi_pq"
	@echo "... demo_ivfpq_indexing"
	@echo "... demo_ivfpq_indexing_gpu"
	@echo "... demo_sift1M"
	@echo "... demo_weighted_kmeans"
	@echo "... faiss"
	@echo "... faiss_gpu_test_helper"
	@echo "... faiss_python_callbacks"
	@echo "... faiss_test"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... swigfaiss"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

