package:
  name: faiss-cpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_url: ../../

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - python {{ python }}
    - intel-openmp # [osx]
    - numpy 1.11.*
    - mkl >=2018

  run:
    - python {{ python }}
    - intel-openmp # [osx]
    - numpy >=1.11
    - blas=*=mkl
    - mkl >=2018

build:
  number: {{ FAISS_BUILD_NUMBER }}

about:
  home: https://github.com/facebookresearch/faiss
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
