if(EXISTS "/home/lvtingxun/Project/tools/faiss/tests/faiss_test[1]_tests.cmake")
  include("/home/lvtingxun/Project/tools/faiss/tests/faiss_test[1]_tests.cmake")
else()
  add_test(faiss_test_NOT_BUILT faiss_test_NOT_BUILT)
endif()
