add_test( BinaryFlat.accuracy /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=BinaryFlat.accuracy]==] --gtest_also_run_disabled_tests)
set_tests_properties( BinaryFlat.accuracy PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestIvlistDealloc.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestIvlistDealloc.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestIvlistDealloc.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestIvlistDealloc.IVFSQ /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestIvlistDealloc.IVFSQ]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestIvlistDealloc.IVFSQ PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestIvlistDealloc.IVFPQ /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestIvlistDealloc.IVFPQ]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestIvlistDealloc.IVFPQ PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IVFPQ.codec /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=IVFPQ.codec]==] --gtest_also_run_disabled_tests)
set_tests_properties( IVFPQ.codec PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IVFPQ.accuracy /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=IVFPQ.accuracy]==] --gtest_also_run_disabled_tests)
set_tests_properties( IVFPQ.accuracy PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFFlatL2 /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFFlatL2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFFlatL2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.PCAIVFFlatL2 /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.PCAIVFFlatL2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.PCAIVFFlatL2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFFlatIP /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFFlatIP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFFlatIP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFSQL2 /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFSQL2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFSQL2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFSQIP /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFSQIP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFSQIP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFPQL2 /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFPQL2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFPQL2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFPQIP /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFPQIP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFPQIP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.IVFBinary /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.IVFBinary]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.IVFBinary PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestLowLevelIVF.ThreadedSearch /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TestLowLevelIVF.ThreadedSearch]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestLowLevelIVF.ThreadedSearch PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MERGE.merge_flat_no_ids /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=MERGE.merge_flat_no_ids]==] --gtest_also_run_disabled_tests)
set_tests_properties( MERGE.merge_flat_no_ids PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MERGE.merge_flat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=MERGE.merge_flat]==] --gtest_also_run_disabled_tests)
set_tests_properties( MERGE.merge_flat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MERGE.merge_flat_vt /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=MERGE.merge_flat_vt]==] --gtest_also_run_disabled_tests)
set_tests_properties( MERGE.merge_flat_vt PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MERGE.merge_flat_ondisk /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=MERGE.merge_flat_ondisk]==] --gtest_also_run_disabled_tests)
set_tests_properties( MERGE.merge_flat_ondisk PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( MERGE.merge_flat_ondisk_2 /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=MERGE.merge_flat_ondisk_2]==] --gtest_also_run_disabled_tests)
set_tests_properties( MERGE.merge_flat_ondisk_2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Threading.openmp /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=Threading.openmp]==] --gtest_also_run_disabled_tests)
set_tests_properties( Threading.openmp PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ONDISK.make_invlists /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ONDISK.make_invlists]==] --gtest_also_run_disabled_tests)
set_tests_properties( ONDISK.make_invlists PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ONDISK.test_add /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ONDISK.test_add]==] --gtest_also_run_disabled_tests)
set_tests_properties( ONDISK.test_add PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ONDISK.make_invlists_threaded /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ONDISK.make_invlists_threaded]==] --gtest_also_run_disabled_tests)
set_tests_properties( ONDISK.make_invlists_threaded PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( test_search_centroid.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=test_search_centroid.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( test_search_centroid.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( test_search_centroid.PCAIVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=test_search_centroid.PCAIVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( test_search_centroid.PCAIVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( test_search_and_return_centroids.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=test_search_and_return_centroids.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( test_search_and_return_centroids.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( test_search_and_return_centroids.PCAIVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=test_search_and_return_centroids.PCAIVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( test_search_and_return_centroids.PCAIVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPO.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TPO.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPO.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPO.IVFPQ /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TPO.IVFPQ]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPO.IVFPQ PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPO.IVFSQ /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TPO.IVFSQ]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPO.IVFSQ PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPO.IVFFlatPP /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TPO.IVFFlatPP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPO.IVFFlatPP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TPOB.IVF /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TPOB.IVF]==] --gtest_also_run_disabled_tests)
set_tests_properties( TPOB.IVF PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PQEncoderGeneric.encode /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=PQEncoderGeneric.encode]==] --gtest_also_run_disabled_tests)
set_tests_properties( PQEncoderGeneric.encode PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PQEncoder8.encode /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=PQEncoder8.encode]==] --gtest_also_run_disabled_tests)
set_tests_properties( PQEncoder8.encode PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PQEncoder16.encode /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=PQEncoder16.encode]==] --gtest_also_run_disabled_tests)
set_tests_properties( PQEncoder16.encode PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SlidingWindow.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=SlidingWindow.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( SlidingWindow.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SlidingWindow.PCAIVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=SlidingWindow.PCAIVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( SlidingWindow.PCAIVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SlidingInvlists.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=SlidingInvlists.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( SlidingInvlists.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( SlidingInvlists.PCAIVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=SlidingInvlists.PCAIVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( SlidingInvlists.PCAIVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ThreadedIndex.SingleException /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ThreadedIndex.SingleException]==] --gtest_also_run_disabled_tests)
set_tests_properties( ThreadedIndex.SingleException PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ThreadedIndex.MultipleException /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ThreadedIndex.MultipleException]==] --gtest_also_run_disabled_tests)
set_tests_properties( ThreadedIndex.MultipleException PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ThreadedIndex.TestReplica /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ThreadedIndex.TestReplica]==] --gtest_also_run_disabled_tests)
set_tests_properties( ThreadedIndex.TestReplica PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ThreadedIndex.TestShards /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=ThreadedIndex.TestShards]==] --gtest_also_run_disabled_tests)
set_tests_properties( ThreadedIndex.TestShards PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TRANS.IVFFlat /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TRANS.IVFFlat]==] --gtest_also_run_disabled_tests)
set_tests_properties( TRANS.IVFFlat PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TRANS.IVFFlatPreproc /home/lvtingxun/Project/tools/faiss/tests/faiss_test [==[--gtest_filter=TRANS.IVFFlatPreproc]==] --gtest_also_run_disabled_tests)
set_tests_properties( TRANS.IVFFlatPreproc PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( faiss_test_TESTS BinaryFlat.accuracy TestIvlistDealloc.IVFFlat TestIvlistDealloc.IVFSQ TestIvlistDealloc.IVFPQ IVFPQ.codec IVFPQ.accuracy TestLowLevelIVF.IVFFlatL2 TestLowLevelIVF.PCAIVFFlatL2 TestLowLevelIVF.IVFFlatIP TestLowLevelIVF.IVFSQL2 TestLowLevelIVF.IVFSQIP TestLowLevelIVF.IVFPQL2 TestLowLevelIVF.IVFPQIP TestLowLevelIVF.IVFBinary TestLowLevelIVF.ThreadedSearch MERGE.merge_flat_no_ids MERGE.merge_flat MERGE.merge_flat_vt MERGE.merge_flat_ondisk MERGE.merge_flat_ondisk_2 Threading.openmp ONDISK.make_invlists ONDISK.test_add ONDISK.make_invlists_threaded test_search_centroid.IVFFlat test_search_centroid.PCAIVFFlat test_search_and_return_centroids.IVFFlat test_search_and_return_centroids.PCAIVFFlat TPO.IVFFlat TPO.IVFPQ TPO.IVFSQ TPO.IVFFlatPP TPOB.IVF PQEncoderGeneric.encode PQEncoder8.encode PQEncoder16.encode SlidingWindow.IVFFlat SlidingWindow.PCAIVFFlat SlidingInvlists.IVFFlat SlidingInvlists.PCAIVFFlat ThreadedIndex.SingleException ThreadedIndex.MultipleException ThreadedIndex.TestReplica ThreadedIndex.TestShards TRANS.IVFFlat TRANS.IVFFlatPreproc)
