FROM nvidia/cuda:10.2-devel-ubuntu18.04

# Install python3, swig, and openblas.
RUN apt-get update && \
        apt-get install -y python3-dev python3-pip swig libopenblas-dev

# Install recent CMake.
RUN apt-get install -y wget && \
        wget -nv -O - https://github.com/Kitware/CMake/releases/download/v3.17.1/cmake-3.17.1-Linux-x86_64.tar.gz | tar xzf - --strip-components=1 -C /usr && \
        apt remove -y wget

# Install numpy/scipy for python tests.
RUN pip3 install numpy scipy
