FROM nvidia/cuda:10.2-devel-ubuntu18.04

RUN apt-get update && apt-get install -y wget git libcublas-dev

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
        bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
ENV PATH="/root/miniconda3/condabin:${PATH}"

RUN conda install conda-build

COPY ./ faiss
WORKDIR /faiss/conda

RUN CUDA_ARCHS="35;52;60;61;70;72;75" \
        conda build faiss-gpu --variants '{ "cudatoolkit": "10.2" }' \
        --no-anaconda-upload -c pytorch --no-test
