# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM nvidia/cuda:10.1-devel-ubuntu18.04

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages wget git libcublas-dev=10.1.0.105-1

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
        bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
ENV PATH="/root/miniconda3/condabin:${PATH}"

RUN conda install -y -q conda-build anaconda-client
RUN conda config --set anaconda_upload yes

RUN sh -c 'cp /usr/include/cublas*.h /usr/local/cuda/include/'
COPY ./ faiss
WORKDIR /faiss/conda
