# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FROM condaforge/miniforge3

RUN apt-get update && apt-get install -y wget git

RUN conda install conda-build

COPY ./ faiss
WORKDIR /faiss/conda

RUN conda build faiss-aarch64 --no-anaconda-upload -c pytorch
