FROM nvidia/cuda:10.1-devel-ubuntu18.04

RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages wget git libcublas-dev=10.1.0.105-1

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
        bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
ENV PATH="/root/miniconda3/condabin:${PATH}"

RUN conda install conda-build

RUN sh -c 'cp /usr/include/cublas*.h /usr/local/cuda/include/'
COPY ./ faiss
WORKDIR /faiss/conda


RUN CUDA_ARCHS="35;52;60;61;70;72;75" \
    conda build faiss-gpu --variants '{ "cudatoolkit": "10.1" }' \
    --no-anaconda-upload -c pytorch --no-test
