add_test( TestGpuDistance.Transposition_RR /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Transposition_RR]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Transposition_RR PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Transposition_RC /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Transposition_RC]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Transposition_RC PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Transposition_CR /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Transposition_CR]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Transposition_CR PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Transposition_CC /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Transposition_CC]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Transposition_CC PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.L1 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.L1]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.L1 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.L1_RC /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.L1_RC]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.L1_RC PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.L1_CR /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.L1_CR]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.L1_CR PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.L1_CC /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.L1_CC]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.L1_CC PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Linf /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Linf]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Linf PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Lp /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Lp]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Lp PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.Canberra /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.Canberra]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.Canberra PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.BrayCurtis /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.BrayCurtis]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.BrayCurtis PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuDistance.JensenShannon /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuDistance [==[--gtest_filter=TestGpuDistance.JensenShannon]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuDistance.JensenShannon PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( TestGpuDistance_TESTS TestGpuDistance.Transposition_RR TestGpuDistance.Transposition_RC TestGpuDistance.Transposition_CR TestGpuDistance.Transposition_CC TestGpuDistance.L1 TestGpuDistance.L1_RC TestGpuDistance.L1_CR TestGpuDistance.L1_CC TestGpuDistance.Linf TestGpuDistance.Lp TestGpuDistance.Canberra TestGpuDistance.BrayCurtis TestGpuDistance.JensenShannon)
