add_test( TestGpuIndexIVFPQ.Query_L2 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Query_L2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Query_L2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Query_L2_MMCodeDistance /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Query_L2_MMCodeDistance]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Query_L2_MMCodeDistance PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Query_IP_MMCodeDistance /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Query_IP_MMCodeDistance]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Query_IP_MMCodeDistance PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Query_IP /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Query_IP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Query_IP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Float16Coarse /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Float16Coarse]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Float16Coarse PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Add_L2 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Add_L2]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Add_L2 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.Add_IP /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.Add_IP]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.Add_IP PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.CopyTo /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.CopyTo]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.CopyTo PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.CopyFrom /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.CopyFrom]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.CopyFrom PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.QueryNaN /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.QueryNaN]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.QueryNaN PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.AddNaN /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.AddNaN]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.AddNaN PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexIVFPQ.UnifiedMemory /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexIVFPQ [==[--gtest_filter=TestGpuIndexIVFPQ.UnifiedMemory]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexIVFPQ.UnifiedMemory PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( TestGpuIndexIVFPQ_TESTS TestGpuIndexIVFPQ.Query_L2 TestGpuIndexIVFPQ.Query_L2_MMCodeDistance TestGpuIndexIVFPQ.Query_IP_MMCodeDistance TestGpuIndexIVFPQ.Query_IP TestGpuIndexIVFPQ.Float16Coarse TestGpuIndexIVFPQ.Add_L2 TestGpuIndexIVFPQ.Add_IP TestGpuIndexIVFPQ.CopyTo TestGpuIndexIVFPQ.CopyFrom TestGpuIndexIVFPQ.QueryNaN TestGpuIndexIVFPQ.AddNaN TestGpuIndexIVFPQ.UnifiedMemory)
