add_test( TestGpuIndexFlat.IP_Float32 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.IP_Float32]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.IP_Float32 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L1_Float32 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L1_Float32]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L1_Float32 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.Lp_Float32 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.Lp_Float32]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.Lp_Float32 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L2_Float32 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L2_Float32]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L2_Float32 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L2_Float32_K1 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L2_Float32_K1]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L2_Float32_K1 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.IP_Float16 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.IP_Float16]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.IP_Float16 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L2_Float16 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L2_Float16]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L2_Float16 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L2_Float16_K1 /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L2_Float16_K1]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L2_Float16_K1 PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.L2_Tiling /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.L2_Tiling]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.L2_Tiling PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.QueryEmpty /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.QueryEmpty]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.QueryEmpty PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.CopyFrom /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.CopyFrom]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.CopyFrom PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.CopyTo /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.CopyTo]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.CopyTo PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TestGpuIndexFlat.UnifiedMemory /home/lvtingxun/Project/tools/faiss/faiss/gpu/test/TestGpuIndexFlat [==[--gtest_filter=TestGpuIndexFlat.UnifiedMemory]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestGpuIndexFlat.UnifiedMemory PROPERTIES WORKING_DIRECTORY /home/lvtingxun/Project/tools/faiss/faiss/gpu/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( TestGpuIndexFlat_TESTS TestGpuIndexFlat.IP_Float32 TestGpuIndexFlat.L1_Float32 TestGpuIndexFlat.Lp_Float32 TestGpuIndexFlat.L2_Float32 TestGpuIndexFlat.L2_Float32_K1 TestGpuIndexFlat.IP_Float16 TestGpuIndexFlat.L2_Float16 TestGpuIndexFlat.L2_Float16_K1 TestGpuIndexFlat.L2_Tiling TestGpuIndexFlat.QueryEmpty TestGpuIndexFlat.CopyFrom TestGpuIndexFlat.CopyTo TestGpuIndexFlat.UnifiedMemory)
