name: Build cmake
inputs:
  opt_level:
    description: 'Compile options / optimization level.'
    required: false
    default: generic
  gpu:
    description: 'Enable GPU support.'
    required: false
    default: OFF
  raft:
    description: 'Enable RAFT support.'
    required: false
    default: OFF
runs:
  using: composite
  steps:
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.11'
        miniconda-version: latest
    - name: Configure build environment
      shell: bash
      run: |
        # initialize Conda
        conda config --set solver libmamba
        conda update -y -q conda
        echo "$CONDA/bin" >> $GITHUB_PATH

        conda install -y -q python=3.11 cmake make swig numpy scipy pytest

        # install base packages for ARM64
        if [ "${{ runner.arch }}" = "ARM64" ]; then
          conda install -y -q -c conda-forge openblas gxx_linux-aarch64 sysroot_linux-aarch64
        fi

        # install base packages for X86_64
        if [ "${{ runner.arch }}" = "X64" ]; then
          # TODO: unpin versions for gxx_linux-64 and sysroot_linux-64 and merge it with ARM64 below
          conda install -y -q -c conda-forge gxx_linux-64=11.2 sysroot_linux-64=2.28
          conda install -y -q mkl=2023 mkl-devel=2023 
        fi


        # install CUDA packages
        if [ "${{ inputs.gpu }}" = "ON" ] && [ "${{ inputs.raft }}" = "OFF" ]; then
          conda install -y -q cuda-toolkit -c "nvidia/label/cuda-11.8.0"
        fi

        # install RAFT packages
        if [ "${{ inputs.raft }}" = "ON" ]; then
          conda install -y -q libraft cuda-version=11.8 cuda-toolkit -c rapidsai-nightly -c "nvidia/label/cuda-11.8.0" -c conda-forge
        fi

        # install test packages
        conda install -y pytest
        if [ "${{ inputs.gpu }}" = "ON" ]; then
          conda install -y -q pytorch pytorch-cuda=11.8 -c pytorch -c nvidia/label/cuda-11.8.0
        else
          conda install -y -q pytorch -c pytorch
        fi
    - name: Build all targets
      shell: bash
      run: |
        eval "$(conda shell.bash hook)"

        args=(
          -DBUILD_TESTING=ON 
          -DBUILD_SHARED_LIBS=ON 
          -DFAISS_ENABLE_GPU=${{ inputs.gpu }} 
          -DFAISS_ENABLE_RAFT=${{ inputs.raft }} 
          -DFAISS_OPT_LEVEL=${{ inputs.opt_level }} 
          -DFAISS_ENABLE_C_API=ON 
          -DPYTHON_EXECUTABLE=$CONDA/bin/python 
          -DCMAKE_BUILD_TYPE=Release 
        )
        if [ "${{ runner.arch }}" = "X64" ]; then
          args+=(
            -DBLA_VENDOR=Intel10_64_dyn 
            -DCMAKE_CUDA_FLAGS=\"-gencode arch=compute_75,code=sm_75\"
          )
        fi
        conda activate
        cmake -B build "${args[@]}" .
        make -k -C build -j$(nproc)
    - name: C++ tests
      shell: bash
      run: |
        export GTEST_OUTPUT="xml:$(realpath .)/test-results/googletest/"
        make -C build test
    - name: Install Python extension
      shell: bash
      working-directory: build/faiss/python
      run: |
        $CONDA/bin/python setup.py install
    - name: Python tests (CPU only)
      if: inputs.gpu == 'OFF'
      shell: bash
      run: |
        pytest --junitxml=test-results/pytest/results.xml tests/test_*.py
        pytest --junitxml=test-results/pytest/results-torch.xml tests/torch_*.py
    - name: Python tests (CPU + GPU)
      if: inputs.gpu == 'ON'
      shell: bash
      run: |
        pytest --junitxml=test-results/pytest/results.xml tests/test_*.py
        pytest --junitxml=test-results/pytest/results-torch.xml tests/torch_*.py
        cp tests/common_faiss_tests.py faiss/gpu/test
        pytest --junitxml=test-results/pytest/results-gpu.xml faiss/gpu/test/test_*.py
        pytest --junitxml=test-results/pytest/results-gpu-torch.xml faiss/gpu/test/torch_*.py
    - name: Test avx2 loading
      if: inputs.opt_level == 'avx2'
      shell: bash
      run: |
        FAISS_DISABLE_CPU_FEATURES=AVX2 LD_DEBUG=libs $CONDA/bin/python -c "import faiss" 2>&1 | grep faiss.so
        LD_DEBUG=libs $CONDA/bin/python -c "import faiss" 2>&1 | grep faiss_avx2.so
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ runner.arch }}-${{ inputs.opt_level }}-${{ inputs.gpu }}-${{ inputs.raft }}
        path: test-results
