name: Build cmake
inputs:
  opt_level:
    description: 'Compile options / optimization level.'
    required: false
    default: generic
  gpu:
    description: 'Enable GPU support.'
    required: false
    default: OFF
  raft:
    description: 'Enable RAFT support.'
    required: false
    default: OFF
runs:
  using: composite
  steps:
    - name: check cpu features
      shell: bash
      run: | 
        echo ARM stuff
        sudo apt-get update -y && sudo apt-get install -y cpuinfo
        cpuinfo | grep -c "Features\t: asimd"
        cpuinfo
        echo AMX stuff
        cpuid -1 | grep AMX and lscpu | grep amx
        cpuid -1
