package:
  name: faiss-gpu
  version: "{{ FAISS_BUILD_VERSION }}"

source:
  git_url: ../../

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - setuptools
    - swig

  host:
    - python {{ python }}
    - intel-openmp # [osx]
    - numpy 1.11.*
    - mkl >=2018
    - cudatoolkit {{ cudatoolkit }}

  run:
    - python {{ python }}
    - intel-openmp # [osx]
    - numpy >=1.11
    - mkl >=2018
    - blas=*=mkl
    - {{ pin_compatible('cudatoolkit') }}

build:
  number: {{ FAISS_BUILD_NUMBER }}
  script_env:
    - CUDA_ROOT
    - CUDA_ARCH

about:
  home: https://github.com/facebookresearch/faiss
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for efficient similarity search and clustering of dense vectors.
